Update cache_gcc.yml

diff --git a/.github/workflows/cache_gcc.yml b/.github/workflows/cache_gcc.yml
--- a/.github/workflows/cache_gcc.yml
+++ b/.github/workflows/cache_gcc.yml
@@ -17,6 +17,14 @@ jobs:
         GCC_64_DIR="$HOME/tc/aarch64-linux-android-14.0"
         GCC_32_DIR="$HOME/tc/arm-linux-androideabi-14.0"
 
+        if ! [ -d "${TC_DIR}" ]; then
+            echo "Clang not found! Cloning to ${TC_DIR}..."
+            if ! git clone --depth=1 https://gitlab.com/moehacker/clang-r498229b ${TC_DIR}; then
+                echo "Cloning failed! Aborting..."
+                exit 1
+            fi
+        fi
+
         if ! [ -d "${GCC_64_DIR}" ]; then
             echo "gcc not found! Cloning to ${GCC_64_DIR}..."
             git clone --depth=1 -b 14 https://github.com/ZyCromerZ/aarch64-zyc-linux-gnu ${GCC_64_DIR}
